version: '3'

services:
  be-blue:
    image: sok5188/gyunpang-be:latest
    environment:
      CONTAINER_COLOR: "blue"

  be-green:
    image: sok5188/gyunpang-be:latest
    environment:
      CONTAINER_COLOR: "green"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"