services:
  be-blue:
    image: sok5188/gyunpang-be:latest
    environment:
      CONTAINER_COLOR: "blue"

  be-green:
    image: sok5188/gyunpang-be:latest
    environment:
      CONTAINER_COLOR: "green"
    volumes:
      - ./pinpoint-agent-3.0.0/pinpoint-bootstrap-3.0.0.jar:/pinpoint-agent/pinpoint-bootstrap-3.0.0.jar

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"