spring:
  kafka:
    bootstrap-servers: { kafka-server }
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      auto-commit: false
      connection-timeout: 290000
      max-lifetime: 90000
  jpa:
    hibernate:
      default-batch-size: 200
      ddl-auto: none
    show-sql: true

kafka:
  topic:
    log: GatewayAPI

mail:
  id: { mail.id }
  password: { mail.password }