spring:
  kafka:
    bootstrap-servers: { kafka-server }
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      default-batch-size: 200
    show-sql: true

kafka:
  topic:
    log: GatewayAPI