name: CI/CD using github actions & docker

# event trigger
on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      # JDK setting
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      # gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test

      # send docker-compose.yml to be1
      - name: Send docker-compose.yml to BE1
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.BE1_PRIVATE_KEY }}
          host: ${{ secrets.BE1_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          source: "./docker-compose.yml"
          target: "/home/ubuntu/"

      # send docker-compose.yml to be2
      - name: Send docker-compose.yml to BE2
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.BE2_PRIVATE_KEY }}
          host: ${{ secrets.BE2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          source: "./docker-compose.yml"
          target: "/home/ubuntu/"

      # send deploy.sh be1
      - name: Send deploy.sh to BE1
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.BE1_PRIVATE_KEY }}
          host: ${{ secrets.BE1_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          source: "./deploy.sh"
          target: "/home/ubuntu/"

      # send deploy.sh be2
      - name: Send deploy.sh to BE2
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.BE2_PRIVATE_KEY }}
          host: ${{ secrets.BE2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          source: "./deploy.sh"
          target: "/home/ubuntu/"

      # docker build & push to hub
      - name: Docker build & push to hub
        if: contains(github.ref, 'master')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/gyunpang-be .
          docker push ${{ secrets.DOCKER_USERNAME }}/gyunpang-be

      # deploy to be1
      - name: Deploy docker at BE1
        uses: appleboy/ssh-action@master
        id: deploy-docker
        if: contains(github.ref, 'master')
        with:
          key: ${{ secrets.BE1_PRIVATE_KEY }}
          host: ${{ secrets.BE1_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/gyunpang-be
            chmod 777 ./deploy.sh
            ./deploy.sh
            sudo docker image prune -f 

      ## deploy to be2
      - name: Deploy docker at BE2
        uses: appleboy/ssh-action@master
        id: deploy-docker
        if: contains(github.ref, 'master')
        with:
          key: ${{ secrets.BE2_PRIVATE_KEY }}
          host: ${{ secrets.BE2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/gyunpang-be
            chmod 777 ./deploy.sh
            ./deploy.sh
            sudo docker image prune -f 
